local ALL_ITEMS = {
    ["ITEM_1"] = "Arrow",
    ["ITEM_2"] = "DIO's Diary", 
    ["ITEM_3"] = "DIO's Bone",
    ["ITEM_4"] = "Corrupted Soul",
    ["ITEM_5"] = "Corrupted Arrow",
    ["ITEM_6"] = "Demonic Scroll",
    ["ITEM_7"] = "Fragment of Death",
    ["ITEM_8"] = "Heavenly Nectar",
    ["ITEM_9"] = "Godly Doctor's Poison",
    ["ITEM_10"] = "Sovereign's Chapter",
    ["ITEM_11"] = "A New Fable",
    ["ITEM_12"] = "Sovereign's Sword",
    ["ITEM_15"] = "Cursed Orb",
    ["ITEM_16"] = "Heart of the Saint",
    ["ITEM_17"] = "Saints Arms",
    ["ITEM_18"] = "Saints Eyes",
    ["ITEM_20"] = "Cosmic Fragments",
    ["ITEM_22"] = "Evil Fragments",
    ["ITEM_23"] = "Tales Of The Universe",
    ["ITEM_24"] = "Watch",
    ["ITEM_25"] = "Bone",
    ["ITEM_26"] = "Yo-Yo",
    ["ITEM_27"] = "Pumpkin",
    ["ITEM_29"] = "Saints Skull",
    ["ITEM_30"] = "Shaper's Essence",
    ["ITEM_35"] = "Dragon Ball",
    ["ITEM_36"] = "Mysterious Hat",
    ["ITEM_37"] = "Bat",
    ["ITEM_39"] = "Requiem Arrow",
    ["ITEM_41"] = "Azakana Mask",
    ["ITEM_42"] = "Ancient Sword",
    ["ITEM_46"] = "Saints Legs",
    ["ITEM_47"] = "Saints Ribcage",
    ["ITEM_51"] = "Saint's Corpse",
    ["ITEM_52"] = "Sword",
    ["ITEM_53"] = "Paintball Gun",
    ["ITEM_54"] = "Bomb",
    ["ITEM_55"] = "Trowel",
    ["ITEM_56"] = "Ban Hammer",
    ["ITEM_57"] = "Slingshot",
    ["ITEM_58"] = "Rocket Launcher",
    ["ITEM_59"] = "Superball",
    ["ITEM_60"] = "Frog",
    
    ["ITEM_61"] = "Hamon Imbued Frog",
    ["ITEM_62"] = "Letter to Jonathan",
    ["ITEM_63"] = "Letter to Joseph",
    ["ITEM_64"] = "Jonathan's Signal",
    ["ITEM_65"] = "Jonathan's Worn Out Gloves",
    ["ITEM_66"] = "Bait Vampire Mask",
    ["ITEM_67"] = "Rundown Mask",
    ["ITEM_71"] = "Joseph's Signal",
    ["ITEM_72"] = "Worn Out Scarf",
    
    ["ITEM_68"] = "Caesar's Headband",
    ["ITEM_69"] = "Aja Stone",
    ["ITEM_70"] = "Clackers",
    ["ITEM_73"] = "Stone Mask",
    ["ITEM_74"] = "Dio's Charm",
    ["ITEM_75"] = "Dio's Remains",
    ["ITEM_76"] = "Heart",
    ["ITEM_77"] = "Gojo's Blindfold",
    ["ITEM_78"] = "Sukuna's Finger",
    ["ITEM_79"] = "Mysterious Fragment",
    ["ITEM_80"] = "Tactical Vest",
    ["ITEM_81"] = "Arm Band",
    ["ITEM_82"] = "Used Arrow",
    ["ITEM_83"] = "Sorcerer's Scarf",
    ["ITEM_84"] = "Ope Devil Fruit",
    ["ITEM_85"] = "Mero Devil Fruit",
    ["ITEM_86"] = "Suna Devil Fruit",
    ["ITEM_87"] = "Law's Cap",
    ["ITEM_88"] = "Knight's Blade",
    ["ITEM_89"] = "Kuma's Book",
    ["ITEM_90"] = "Green Baby",
    ["ITEM_91"] = "Blood of Joseph",
    ["ITEM_92"] = "Bouquet Of Flowers",
    ["ITEM_93"] = "Claw Fragment",
    ["ITEM_94"] = "Sanji's Cookbook",
    ["ITEM_95"] = "Baroque Works Contractor Den Den",
    ["ITEM_96"] = "Joestar Blood Vial",
    ["ITEM_97"] = "Golden Hook",
    ["ITEM_98"] = "True Stone Mask",
    
    ["ITEM_525"] = "Phoenix Gemstone",
    ["ITEM_526"] = "Kinetic Gemstone",
    ["ITEM_527"] = "Monochromatic Gemstone",
    ["ITEM_528"] = "Soul Gemstone",
    ["ITEM_529"] = "Draconic Gemstone",
    ["ITEM_530"] = "Monochromatic Orb",
    ["ITEM_531"] = "Kinetic Orb",
    ["ITEM_532"] = "Cursed Gemstone",
    ["ITEM_533"] = "Bisento",
    ["ITEM_534"] = "Slime Energy",
    
    ["ITEM_535"] = "Busoshoku Manual",
    ["ITEM_536"] = "Haoshoku Manual",
    ["ITEM_537"] = "Kenbunshoku Manual",
    ["ITEM_538"] = "Gomu Devil Fruit",
    ["ITEM_539"] = "Hito Devil Fruit",
    ["ITEM_540"] = "Haki Shard",
    
    ["ITEM_541"] = "Limitless Technique Scroll",
    ["ITEM_542"] = "Wheel of Dharma",
    ["ITEM_543"] = "Split Soul Katana",
    ["ITEM_544"] = "Playful Cloud",
    ["ITEM_545"] = "Inverted Spear of Heaven",
    ["ITEM_546"] = "Heavenly Restriction Awakening",
    ["ITEM_547"] = "Simple Domain Essence",
    ["ITEM_548"] = "Cursed Arm",
    ["ITEM_549"] = "Death Painting",
    ["ITEM_550"] = "Shrine Item",
    
    ["ITEM_551"] = "King of Curses Shard",
    ["ITEM_552"] = "Remembrance of the Fallen",
    ["ITEM_553"] = "The Vessel Shard",
    ["ITEM_554"] = "Remembrance of the Vessel",
    ["ITEM_555"] = "Sorcerer Killer Shard",
    ["ITEM_556"] = "Remembrance of the Sorcerer Killer",
    ["ITEM_557"] = "Remembrance of the Strongest",
    
    ["ITEM_580"] = "Gun Parts",
    ["ITEM_581"] = "Chest Key",
    ["ITEM_582"] = "Inhumane Spirit",
    ["ITEM_583"] = "Cursed Apple",
    ["ITEM_600"] = "Meat On A Bone",
    ["ITEM_601"] = "West Blue Juice",
    ["ITEM_602"] = "Manual of Gryphon's Techniques",
    ["ITEM_620"] = "Candy Bag",
    ["ITEM_750"] = "Altered Steel Ball",
    ["ITEM_800"] = "Stocking",
    ["ITEM_801"] = "Candy Cutlass Blade",
    
    ["ITEM_802"] = "Knife",
    ["ITEM_803"] = "Flamethrower",
    ["ITEM_804"] = "Eyelander",
    ["ITEM_805"] = "Grenade Launcher",
    ["ITEM_806"] = "Medic's Equipment",
    ["ITEM_807"] = "Chargin' Targe",
    ["ITEM_808"] = "Vampirism Mastery",
    
    ["ITEM_809"] = "Coal",
    ["ITEM_810"] = "Metal Scraps",
    ["ITEM_811"] = "Metal Ingot",
    ["ITEM_812"] = "Light of Hope",
    ["ITEM_813"] = "Nanotech Fragments",
    
    ["ITEM_814"] = "Anshen's Chestplate",
    ["ITEM_815"] = "Anshen's Helmet", 
    ["ITEM_816"] = "Anshen's Wing Set",
    ["ITEM_817"] = "Anshen's Arm Plates",
    ["ITEM_818"] = "Anshen's Leg Plates",
    ["ITEM_819"] = "Anshen's Lance",
    ["ITEM_820"] = "Anshen's Suit",
    ["ITEM_821"] = "Metal Loot",
    ["ITEM_822"] = "Coal Loot",
    
    ["ITEM_828"] = "Locacaca",
    ["ITEM_829"] = "Spin Energy Fragment",
    
    ["ITEM_830"] = "Whitebeard's Calamity Force",
    ["ITEM_831"] = "Shanks' Calamity Force",
    ["ITEM_832"] = "Kars' Calamity Force",
    ["ITEM_833"] = "Umbra's Calamity Force",
    ["ITEM_834"] = "Mahoraga's Calamity Force",
    ["ITEM_835"] = "Shadow's Calamity Force",
    ["ITEM_836"] = "The Denzien Of Hell's Calamity Force",
    ["ITEM_837"] = "Sukuna's Calamity Force",
    ["ITEM_838"] = "The Total Force Of Calamity"
}

local BLACKMARKET_BLACKLIST = {
    "ITEM_61", "ITEM_62", "ITEM_63", "ITEM_64", "ITEM_65", 
    "ITEM_66", "ITEM_67", "ITEM_71", "ITEM_72",
    
    "ITEM_1", "ITEM_5", "ITEM_6", "ITEM_7", "ITEM_16", "ITEM_26",
    "ITEM_29", "ITEM_51", "ITEM_75", "ITEM_77", "ITEM_78", "ITEM_79",
    "ITEM_80", "ITEM_81", "ITEM_82", "ITEM_83", "ITEM_84", "ITEM_87",
    "ITEM_88", "ITEM_90", "ITEM_91", "ITEM_92", "ITEM_93", "ITEM_95",
    "ITEM_96", "ITEM_97", "ITEM_98", "ITEM_525", "ITEM_527", "ITEM_528",
    "ITEM_529", "ITEM_532", "ITEM_533", "ITEM_534", "ITEM_536", "ITEM_538",
    "ITEM_539", "ITEM_551", "ITEM_552", "ITEM_553", "ITEM_554", "ITEM_555",
    "ITEM_556", "ITEM_557", "ITEM_582", "ITEM_583", "ITEM_602", "ITEM_620",
    "ITEM_800", "ITEM_801", "ITEM_808", "ITEM_809", "ITEM_811", "ITEM_812",
    "ITEM_813", "ITEM_814", "ITEM_815", "ITEM_816", "ITEM_817", "ITEM_818",
    "ITEM_819", "ITEM_820", "ITEM_828", "ITEM_830", "ITEM_831", "ITEM_832",
    "ITEM_833", "ITEM_834", "ITEM_835", "ITEM_836", "ITEM_837", "ITEM_838"
}

return {
    ALL_ITEMS = ALL_ITEMS,
    BLACKMARKET_BLACKLIST = BLACKMARKET_BLACKLIST
}
